apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-be-config
  labels:
    {{- include "prognose.labels" (dict "context" . "component" "backend") | nindent 4 }}
data:
  # Application Configuration
  SERVER_PORT: {{ .Values.be.containerPort | quote }}
  
  # Database Configuration
  DB_TYPE: {{ .Values.be.config.databaseType | quote }}
  DB_URL: {{ include "prognose.database.url" . }}
  
  # Keycloak Configuration  
  KEYCLOAK_AUTH_SERVER_URL: {{ .Values.be.config.keycloakAuthServerUrl | quote }}
  KEYCLOAK_REALM: {{ .Values.be.config.keycloakRealm | quote }}
  KEYCLOAK_CLIENT_ID: {{ .Values.be.config.keycloakClientId | quote }}
  
  # CORS Configuration
  FRONTEND_APP_URL: "http://{{ .Values.fe.ingress.host }}/"
