apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-be-ingress
  labels:
    {{- include "prognose.labels" (dict "context" . "component" "backend") | nindent 4 }}
  annotations:
    # Fondamentale per evitare il redirect su HTTPS (e il CONNECTION_REFUSED)
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # Manteniamo l'errore 418 (I'm a teapot) che avevi gi√†
    nginx.ingress.kubernetes.io/custom-http-errors: "418"
spec:
  # Ho corretto il puntamento a be.ingress per coerenza con il file
  ingressClassName: {{ .Values.be.ingress.ingressClassName | default "nginx" }}
  rules:
    - host: {{ .Values.be.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-be-service
                port:
                  number: {{ .Values.be.containerPort }}
            path: {{ .Values.be.ingress.path }}
            pathType: Prefix
  # Sezione TLS rimossa completamente
