apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-be-ingress
  labels:
    {{- include "prognose.labels" (dict "context" . "component" "backend") | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/custom-http-errors: "418"
spec:
  ingressClassName: {{ .Values.fe.ingress.ingressClassName | default "nginx" }}
  rules:
    - host: {{ .Values.be.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-be-service
                port:
                  number: {{ .Values.be.containerPort }}
            path: {{ .Values.be.ingress.path }}
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.be.ingress.host }}
      secretName: prognose-be-ingress-tls
