apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-fe-ingress
  labels:
    {{- include "prognose.labels" (dict "context" . "component" "frontend") | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: {{ .Values.be.ingress.ingressClassName | default "nginx" }}
  rules:
    - host: {{ .Values.fe.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-fe-service
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.fe.ingress.host }}
      secretName: prognose-fe-ingress-tls
